AWSTemplateFormatVersion: 2010-09-09
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: baba-text-bot-cluster
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Secrets:
            - Name: DISCORD_BOT_TOKEN
              ValueFrom: !Ref botTokenSecretArn
          Essential: true
          Image: !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/fargate-task-definition
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs
          Name: baba-text-bot
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      family: baba-text-bot-task-family
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: baba-text-bot
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref ECSSubnet
      TaskDefinition: !Ref ECSTaskDefinition

Parameters:
  botTokenSecretArn:
    Description: ARN of secret containing the bot token
    Type: String
  Image:
    Description: Image to deploy
    Type: String 
  ECSExecutionRoleArn:
    Description: ARN of the execution role (needs AmazonECSTaskExecutionRolePolicy + SecretsManagerRead)
    Type: String
  ECSSecurityGroup:
    Description: Id of the security group the container will run in (no ingress, only egress)
    Type: String
  ECSSubnet:
    Description: If of the subnet the container will run in (no ingress, only egress)
    Type: String



